# Generated by Django 4.1 on 2022-09-28 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
